"""add new schema for timestamp

Revision ID: 07721c1ce698
Revises: 4514a6d03203
Create Date: 2021-08-24 09:00:01.571653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07721c1ce698'
down_revision = '4514a6d03203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_pitches_timestamp'), 'pitches', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitches_timestamp'), table_name='pitches')
    op.drop_column('pitches', 'timestamp')
    # ### end Alembic commands ###
